<?php

return array(
    'setCustomFields' => ["GET", '/setCustomFields'],
    'getCustomFields' => ["GET", '/getCustomFields'],
    'approveMembership' => ["GET", '/approveMembership'],
    'getPendingMemberships' => ["GET", '/getPendingMemberships'],
    'getMembershipModerationMode' => ["GET", '/getMembershipModerationMode'],
    'setMembershipModerationMode' => ["GET", '/setMembershipModerationMode'],
    'getVerificationRequiredMode' => ["GET", '/getVerificationRequiredMode'],
    'setVerificationRequiredMode' => ["GET", '/setVerificationRequiredMode'],
    'getReadOnlyMode' => ["GET", '/getReadOnlyMode'],
    'setReadOnlyMode' => ["GET", '/setReadOnlyMode'],
    'getAllModes' => ["GET", '/getAllModes'],
    'setAllModes' => ["GET", '/setAllModes'],
    'getObjectCounts' => ["GET", '/getObjectCounts'],
    'getId' => ["GET", '/getId'],
    'deleteMember' => ["GET", '/deleteMember'],
    'getPendingComments' => ["GET", '/getPendingComments'],
    'deletePendingComment' => ["GET", '/deletePendingComment'],
    'approvePendingComment' => ["GET", '/approvePendingComment'],
    'setCommentModeration' => ["GET", '/setCommentModeration'],
    'setBlogEditor' => ["GET", '/setBlogEditor'],
    'setFounderPassword' => ["GET", '/setFounderPassword'],
    'getCommentModeration' => ["GET", '/getCommentModeration'],
    'getSingleSignonKey' => ["GET", '/getSingleSignonKey'],
);

/*
if($kernel->graph() instanceof \PhoNetworksAutogenerated\Network) {
    $server->get(
        'setAbout', function (Request $request, Response $response) use ($controllers, $kernel) {
            $controllers["administration"]->setAbout($request, $response, $kernel);
        }
    );
    // GET /administration/about
    $server->get(
        'getAbout', function (Request $request, Response $response) use ($controllers, $kernel) {
            $controllers["administration"]->getAbout($request, $response, $kernel);
        }
    );
}
*/