<?php

return \GraphJS\Utils::convertLegacyRoutes([
    ["GET", '/setCustomFields','setCustomFields'],
    ["GET", '/getCustomFields','getCustomFields'],
    ["GET", '/approveMembership','approveMembership'],
    ["GET", '/getPendingMemberships','getPendingMemberships'],
    ["GET", '/getMembershipModerationMode','getMembershipModerationMode'],
    ["GET", '/setMembershipModerationMode','setMembershipModerationMode'],
    ["GET", '/getVerificationRequiredMode','getVerificationRequiredMode'],
    ["GET", '/setVerificationRequiredMode','setVerificationRequiredMode'],
    ["GET", '/getReadOnlyMode','getReadOnlyMode'],
    ["GET", '/setReadOnlyMode','setReadOnlyMode'],
    ["GET", '/getAllModes','getAllModes'],
    ["GET", '/setAllModes','setAllModes'],
    ["GET", '/getObjectCounts','getObjectCounts'],
    ["GET", '/getId','getId'],
    ["GET", '/deleteMember','deleteMember'],
    ["GET", '/getPendingComments','getPendingComments'],
    ["GET", '/deletePendingComment','deletePendingComment'],
    ["GET", '/approvePendingComment','approvePendingComment'],
    ["GET", '/setCommentModeration','setCommentModeration'],
    ["GET", '/setBlogEditor','setBlogEditor'],
    ["GET", '/setFounderPassword','setFounderPassword'],
    ["GET", '/getCommentModeration','getCommentModeration'],
    ["GET", '/getSingleSignonKey','getSingleSignonKey']
]);

/*
if($kernel->graph() instanceof \PhoNetworksAutogenerated\Network) {
    $server->get(
        'setAbout', function (Request $request, Response $response) use ($controllers, $kernel) {
            $controllers["administration"]->setAbout($request, $response, $kernel);
        }
    );
    // GET /administration/about
    $server->get(
        'getAbout', function (Request $request, Response $response) use ($controllers, $kernel) {
            $controllers["administration"]->getAbout($request, $response, $kernel);
        }
    );
}
*/