<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GraphJS\Controllers;

use Psr\Http\Message\ResponseInterface;
use React\Http\Response;
use Psr\Http\Message\ServerRequestInterface;
use Pho\Kernel\Kernel;
use PhoNetworksAutogenerated\User;
use Rakit\Validation\Validator;


/**
 * An abstract controller that includes common operations in GraphJS
 * 
 * @author Emre Sokullu <emre@phonetworks.org>
 */
abstract class AbstractController extends  \Pho\Server\Rest\Controllers\AbstractController
{
    protected $validator;
    const SESSION_FAIL_MESSAGE = "Session required.";
    const INVALID_HASH_MESSAGE = "Invalid hash.";

    /**
     * Constructor
     *
     * @param \Pho\Kernel\Kernel $kernel
     * @param boolean $jsonp
     */
    public function __construct(Kernel $kernel, bool $jsonp = false)
    {
        $this->validator = new Validator();
        parent::__construct($kernel, $jsonp);
    }

    /**
     * {@inheritDoc}
     * 
     * The only difference from parent's (pho-server-rest)
     * is that this one always return in HTTP 200.
     *
     * @param ResponseInterface|null $response
     * @param string $message
     * @param integer $code
     * 
     * @return Response
     */
    public function fail(?ResponseInterface $response = null, string $message = "", int $code = 200): Response
    {
        return parent::fail($response, $message, $code);
    }

    /**
     * Fail message when not logged in
     *
     * @param ResponseInterface $response
     * @return void
     */
    protected function failSession(ResponseInterface $response)
    {
        return $this->fail($response, static::SESSION_FAIL_MESSAGE);
    }

    /**
     * Fail message when not admin
     *
     * @param ResponseInterface $response
     * @return void
     */
    protected function failHash(ResponseInterface $response)
    {
        return $this->fail($response, static::INVALID_HASH_MESSAGE);
    }

    /**
     * Is membership moderated?
     *
     * @return boolean
     */
    protected function isMembershipModerated()
    {
        return 
            isset($this->kernel->graph()->attributes()->MembershipModerated) 
            &&
            (bool) $this->kernel->graph()->getMembershipModerated();
    }

    /**
     * Is the site/network read-only?
     *
     * @return boolean
     */
    protected function isReadOnly()
    {
        if(!isset($this->kernel->graph()->attributes()->ReadOnly))
            return false;
        return (bool) $this->kernel->graph()->getReadOnly();
    }

    /**
     * Is verification required for new members?
     *
     * @return boolean
     */
    protected function isVerificationRequired()
    {
        if(!isset($this->kernel->graph()->attributes()->VerificationRequired))
            return false;
        return (bool) $this->kernel->graph()->getVerificationRequired();
    }

    /**
     * Paginate a given array
     *
     * @param array $assets
     * @param array $queryParams
     * @param ?int  $maxCount
     * @return array
     */
    protected function paginate(array $assets, array $queryParams, ?int $maxCount = null): array
    {
        // find out offset
        $offset = 0;
        if(isset($queryParams["offset"])&&is_numeric($queryParams["offset"])) {
            $offset = (int) $queryParams["offset"];
        }

        // find out count
        if(isset($queryParams["count"])&&is_numeric($queryParams["count"])&&$queryParams["count"]!=0) {
            $count = (int) $queryParams["count"];
        }
        else {
            $count = (int) ($maxCount ?? count($blogs));
        }

        return array_slice($assets, $offset, $count, true);
    }

    /**
     * Checks if the password is valid
     *
     * @param string $password
     * @return boolean
     */
    protected function checkPasswordFormat(string $password): bool
    {
        return preg_match("/[0-9A-Za-z!@#$%_]{5,15}/", $password);
    }
}
