<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GraphJS\Controllers;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;

use Pho\Kernel\Kernel;
use PhoNetworksAutogenerated\User;
use PhoNetworksAutogenerated\Thread;
use PhoNetworksAutogenerated\UserOut\Start;
use PhoNetworksAutogenerated\UserOut\Reply;
use Pho\Lib\Graph\ID;
use Pho\Lib\Graph\TailNode;

/**
 * Takes care of Feed
 * 
 * @author Emre Sokullu <emre@phonetworks.org>
 */
class FeedController extends AbstractController
{

    public function generateFeedToken(ServerRequestInterface $request, ResponseInterface $response)
    {
        $data = $request->getQueryParams();
        $validation = $this->validator->validate($data, [
            'id' => 'required',
            'type' => 'required',
        ]);
        if($validation->fails()) {
            return $this->fail($response, "Type and/or id fields unavailable.");
            
        }
        if($data["type"]!="wall"&&$data["type"]!="user"&&$data["type"]!="timeline") {
            return $this->fail($response, "Invalid type.");
            
        }
        $client = new \GetStream\Stream\Client(getenv("STREAM_KEY"), getenv("STREAM_SECRET"));
        $feed = $client->feed($data["type"], $data["id"]);
        $token = $feed->getToken();
        return $this->succeed($response, [
            "token" => $token
        ]);
    }
}
