<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 namespace GraphJS\Controllers;

use CapMousse\ReactRestify\Http\Request;
use CapMousse\ReactRestify\Http\Response;
use CapMousse\ReactRestify\Http\Session;
use Pho\Kernel\Kernel;
use Valitron\Validator;
use PhoNetworksAutogenerated\User;
use PhoNetworksAutogenerated\UserOut\Follow;
use Pho\Lib\Graph\ID;


/**
 * Takes care of Members
 * 
 * @author Emre Sokullu <emre@phonetworks.org>
 */
class MembersController extends AbstractController
{
    /**
     * Get Members
     *
     * @param Request  $request
     * @param Response $response
     * @param Kernel   $kernel
     * 
     * @return void
     */
    public function getMembers(Request $request, Response $response, Kernel $kernel)
    {
        $nodes = $kernel->graph()->members();
        $members = [];
        foreach($nodes as $node) {
            if($node instanceof User) {
                $members[(string) $node->id()] = [
                    "username" => (string) $node->getUsername(),
                    "avatar" => (string) $node->getAvatar()
                ];
            }
        }
        $this->succeed($response, ["members" => $members]);
    }
 
    /**
     * Follow someone
     *
     * id
     *
     * @param Request  $request
     * @param Response $response
     * @param Kernel   $kernel
     * 
     * @return void
     */
    public function follow(Request $request, Response $response, Session $session, Kernel $kernel)
    {
        if(is_null($id = $this->dependOnSession(...\func_get_args()))) {
            $this->fail($response, "Session required");
        }
        $data = $request->getQueryParams();
        $v = new Validator($data);
        $v->rule('required', ['id']);
        if(!$v->validate()) {
            $this->fail($response, "Valid user ID required.");
            return;
        }
        if(!preg_match("/^[0-9a-fA-F][0-9a-fA-F]{30}[0-9a-fA-F]$/", $data["id"])) {
            $this->fail($response, "Invalid ID");
            return;
        }
        $i = $kernel->gs()->node($id);
        $followee = $kernel->gs()->node($data["id"]);
        if(!$i instanceof User) {
            $this->fail($response, "Session owner not a User");
            return;
        }
        if(!$followee instanceof User) {
            $this->fail($response, "Followee not a User");
            return;
        }
        $i->follow($followee);
        $this->succeed($response);
    }

    /**
     * Unfollow someone
     *
     * id
     *
     * @param Request  $request
     * @param Response $response
     * @param Kernel   $kernel
     * 
     * @return void
     */
    public function unfollow(Request $request, Response $response, Session $session, Kernel $kernel)
    {
        if(is_null($id = $this->dependOnSession(...\func_get_args()))) {
            $this->fail($response, "Session required");
        }
        $data = $request->getQueryParams();
        $v = new Validator($data);
        $v->rule('required', ['id']);
        if(!$v->validate()) {
            $this->fail($response, "Valid user ID required.");
            return;
        }
        if(!preg_match("/^[0-9a-fA-F][0-9a-fA-F]{30}[0-9a-fA-F]$/", $data["id"])) {
            $this->fail($response, "Invalid ID");
            return;
        }
        $i = $kernel->gs()->node($id);
        $followee = $kernel->gs()->node($data["id"]);
        if(!$i instanceof User) {
            $this->fail($response, "Session owner not a User");
            return;
        }
        if(!$followee instanceof User) {
            $this->fail($response, "Followee not a User");
            return;
        }
        $follow_edges = $i->edges()->to($followee->id(), Follow::class);
        if(count($follow_edges)!=1) {
            $this->fail($response, "No follow edge found");
            return;
        }
        $follow_edges->current()->destroy();
        $this->succeed($response);
    }

}
