<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 namespace GraphJS\Controllers;

use CapMousse\ReactRestify\Http\Request;
use CapMousse\ReactRestify\Http\Response;
use CapMousse\ReactRestify\Http\Session;
use Pho\Kernel\Kernel;
use PhoNetworksAutogenerated\User;
use Pho\Lib\Graph\ID;


 /**
 * Takes care of Notifications
 * 
 * @author Emre Sokullu <emre@phonetworks.org>
 */
class NotificationsController extends AbstractController
{

    public function count(Request $request, Response $response, Session $session, Kernel $kernel)
    {
        if(is_null($id = $this->dependOnSession(...\func_get_args()))) {
            return;
        }
        $i = $kernel->gs()->node($id);
        if(!$i instanceof User) {
            $this->fail($response, "Session Problem");
            return;
        }
        $ret = [];
        $c=0;
        $ret["count"] = $i->notifications()->count();
        $this->succeed($response, $ret);
    }

    public function read(Request $request, Response $response, Session $session, Kernel $kernel)
    {
        if(is_null($id = $this->dependOnSession(...\func_get_args()))) {
            return;
        }
        $i = $kernel->gs()->node($id);
        if(!$i instanceof User) {
            $this->fail($response, "Session Problem");
            return;
        }
        $ret = [];
        $c=0;
        $ret["count"] = $i->notifications()->count();
        //error_log("Count is: ". $ret["count"]);
        $notifications = $i->notifications()->read(20);
        //error_log(print_r($notifications, true));
        error_log("started");
        foreach($notifications as $notification) {
            error_log(print_r($notification->toArray(), true));
            try {
                $ret["data"][$c]["actor"]["username"] =  $notification->edge()->tail()->node()->getUsername();
                $ret["data"][$c]["actor"]["avatar"] =  $notification->edge()->tail()->node()->getAvatar();
                $ret["data"][$c]["actor"]["id"] =  (string) $notification->edge()->tail()->node()->id();
                $ret["data"][$c]["label"] =  $notification->label();
                $ret["data"][$c]["target"]["id"] =  (string) $notification->edge()->head()->node()->id();
                $c+=1;
            }
            catch(\Exception $e) {
                error_log("There was an exception: ".$e->getMessage());
            }
        }
        $this->succeed($response, $ret);
    }
}