<?php
/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace GraphPress\Controllers;

use CapMousse\ReactRestify\Http\Request;
use CapMousse\ReactRestify\Http\Response;
use CapMousse\ReactRestify\Http\Session;
use Pho\Kernel\Kernel;


class AuthenticationController extends \Pho\Server\Rest\Controllers\AbstractController 
{
    public function signup(Request $request, Response $response, Session $session, Kernel $kernel)
    {
        $data = $request->getQueryParams();
        // do I have to put these validations here?
        // shouldn't the schema take care of this?
        // or is it already?
        $v = new Valitron\Validator($data);
        $v->rule('required', ['email', 'password']);
        $v->rule('email', 'email');
        if(!$v->validate()) {
            $this->fail($response, "Valid email and password required.");
        }
        if(!preg_match("/^[0-9A-Za-z!@#$%_]{5, 15}$/", $data["password"])) {
            $this->fail($response, "Invalid password");
        }
        $new_user = new \PhoNetworksAutogenerated\User($kernel, $kernel->graph(), $data["email"], $data["password"]);
        $session->set($request, "id", (string) $new_user->id());
        $response->writeJson([
            "status"=>"success", 
            "id" => (string) $new_user->id()
        ])->end();
    }

    public function login(Request $request, Response $response, Session $session)
    {

    }

    public function logout(Request $request, Response $response, Session $session) 
    {
        //$session->start($request, $response);
        $session->set($request, "gun", null);
        $response->writeJson(
            ["status"=>"success"]
        )->end();
    }

    

    public function whoami(Request $request, Response $response, Session $session)
    {

        //$session->start($request, $response);
        $response->writeJson(
            ["whoami"=>$session->get($request, "gun")]
        )->end();
    }

}