<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 namespace GraphPress\Controllers;

use CapMousse\ReactRestify\Http\Request;
use CapMousse\ReactRestify\Http\Response;
use CapMousse\ReactRestify\Http\Session;
use Pho\Kernel\Kernel;
use Valitron\Validator;
use PhoNetworksAutogenerated\User;
use Pho\Lib\Graph\ID;


class ContentController extends \Pho\Server\Rest\Controllers\AbstractController 
{
    public function star(Request $request, Response $response, Session $session, Kernel $kernel, string $id, string $url)
    {
        $i = $kernel->gs()->node($id);
        // query if such page exists
        // if not create.
        $i->star();
        $nodes = $kernel->graph()->members();
        $members = [];
        foreach($nodes as $node) {
            if($node instanceof User)
                $members[] = (string) $node->id();
        }
        $response->writeJson([
            "status"=>"success", 
            "members" => $members
        ])->end();
    }

}